#This config file is specificated for theme demo page : https://riino.site/jekyll-theme-panda/
#Please do not use this config directly if you desire to use this repo as your blog.
title: low illuminance
author: riino
remote_theme: sorphwer/jekyll-theme-panda
email: riino@gmail.com
SEOTitle: low illuminance
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://li.riino.site" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twitter_name
github_username: github_name 
github_url: https://github.com/sorphwer
repo_url: https://github.com/sorphwer/jekyll-theme-panda
theme_version: 0.1.1
permalink: /:year-:month-:day-:title:output_ext
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
- jekyll-remote-theme
- jekyll-paginate
paginate: 10

toc:
  min_level: 1 # default: 1
  max_level: 4 # default: 6
sass:
    sass_dir: _sass
    style: compressed

navigation:
- text: Home
  url: ./index.html
- text: Albums
  url: ./albums
  layout: albumlist
- text: Presets
  url: ./presets
  layout: presetlist
# - text: Visios
#   url: ./visios
- text: contact
  url: ./contact
  layout: default

dropdown_header: low illu. #will only exist if dropdown array below has item(s)
dropdown:
- text: blog
  url: riino.site
# - text: drop2.
#   url: example.com

footer_text:
- low illuminance by Riino
- All Rights Reserved.

hoster_logo: /assets/img/logo_Nest.png
hoster_logo_link: https://github.com/sorphwer
hoster_logo_alt: Github
hoster_text:
- Nest of Etamine - 10th Anniversary
- 2012-2022